blog/urls.py
from django.urls import path
from .views import post_list, post_detail, PostListView, post_share, post_comment, post_search
from .feeds import LatestPostsFeed

app_name = 'blog'
urlpatterns = [
    path('', post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', post_detail, name='post_detail'),
    path('<int:post_id>/share/', post_share, name='post_share'),
    path('<int:post_id>/comment/', post_comment, name='post_comment'),
    path('tag/<slug:tag_slug>/', post_list, name="post_list_by_tag"),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', post_search, name='post_search')
]

django_project/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from blog.sitemaps import PostSitemap
sitemaps = {
    'posts': PostSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.urls import reverse
from taggit.managers import TaggableManager

# Create your models here.
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    # unique for date hace que este campo solo pueda ser unico por la fecha guardada en publish
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    # auto_now_add solo agrega la fecha cuando el archivo es creado
    created = models.DateTimeField(auto_now_add=True)
    # auto_now actualiza la fecha cuando el objeto es guardado con .save() por lo que cambiara cuando se actualiza
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status, default=Status.DRAFT)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='blog_posts')
    tags = TaggableManager()

    # MANAGERS
    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ['-publish']
        indexes = [models.Index(fields=['-publish'])]

    def __str__(self):
        return self.title
    
    # esta funcion nos permite crear un url absoluto del objeto, para ello en el reverse le mandamos la url que se encargara de mostrar el elemento y el ID del elemento
    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[
            self.publish.year,
            self.publish.month,
            self.publish.day,
            self.slug
        ])


class Comment(models.Model):
    # Creamos la llave foranea a los post, con related_name podemos declarar la manera en que accederemos a los comentarios desde los posts si no es agregado Django lo crea automaticamente con el nombre del model mas _set (en este caso comment_set)
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    class Meta:
        ordering = ["created"]
        indexes = [models.Index(fields=['created'])]

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.views.decorators.http import require_POST
from django.core.mail import send_mail
from django.db.models import Count
from taggit.models import Tag
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.contrib.postgres.search import TrigramSimilarity

from blog.forms import EmailPostForm, CommentForm, SearchForm
from .models import Post

# Create your views here.
def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(
            Tag,
            slug=tag_slug
        )
        post_list = post_list.filter(tags__in=[tag])
    # creamos el paginator con la lista y la cantidad de elementos por pagina
    paginator = Paginator(post_list, 3)
    # obtenemos el numero de pagina
    page_number = request.GET.get('page', 1)
    # del paginator obtenemos la pagina deseada
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        # si es un numero de pagina invalido vamos a obtener la ultima pagina
        posts = paginator.page(paginator.num_pages)
    context = {
        'posts': posts,
        'tag': tag 
    }
    return render(request, 'blog/post/list.html', context)


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_detail(request, year, month, day, post):
    post = get_object_or_404(
        Post,
        status=Post.Status.PUBLISHED,
        slug=post,
        publish__year=year,
        publish__month=month,
        publish__day=day
    )
    comments = post.comments.filter(active=True)
    form = CommentForm()
    # post similares
    # obtenemos los id y lo ponemos ponemos en una lista simple
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(
        tags__in=post_tags_ids
    ).exclude(
        id=post.id
    )
    # con annotate creamos un nuevo campo con el nombre same_tags que guarda la cantidad de tags en comun
    similar_posts = similar_posts.annotate(
        same_tags=Count('tags')
    ).order_by('-same_tags', '-publish')[:4]
    context = {
        'post': post,
        'comments': comments,
        'form': form,
        'similar_posts': similar_posts
    }
    return render(request, 'blog/post/detail.html', context)


def post_share(request, post_id):
    post = get_object_or_404(
        Post,
        id=post_id,
        status=Post.Status.PUBLISHED
    )
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = (
                f"{cd['name']} ({cd['email']}) "
                f"recommends you read {post.title}"
            )
            message = (
                f"Read {post.title} at {post_url}\n\n"
                f"{cd['name']}\'s comments: {cd["comments"]}"
            )
            sent = True if send_mail(
                subject=subject,
                message=message,
                from_email=None,
                recipient_list=[cd['to']]
            ) == 1 else False
    else:
        form = EmailPostForm()
    context = {
        'post': post,
        'form': form,
        'sent': sent
    }
    return render(request, 'blog/post/share.html', context)


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(
        Post,
        id=post_id,
        status=Post.Status.PUBLISHED
    )
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    context = {
        'post': post,
        'form': form,
        'comment': comment
    }
    return render(
        request,
        'blog/post/comment.html',
        context
    )


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            # search_vector = SearchVector('title', weight='A', config='spanish') + SearchVector('body', weight='B', config='spanish')
            # search_query = SearchQuery(query, config='spanish')
            results = (Post.published.annotate(
                similarity=TrigramSimilarity('title', query)
                # search=search_vector,
                # rank=SearchRank(search_vector, search_query)
            )).filter(
                # rank__gte=0.3
                similarity__gt=0.1
            ).order_by(
                # '-rank'
                '-similarity'
            )
    context = {
        'form': form,
        'query': query,
        'results': results
    }
    return render(
        request,
        'blog/post/search.html',
        context
    )

templates/blog/post/comment.html
{% extends "blog/_base.html" %}
{% block title %}Add a comment{% endblock title %}
{% block content %}
    {% if comment %}
        <h2>Your comment has been added.</h2>
        <p>
            <a href="{{ post.get_absolute_url }}">Back to the post</a>
        </p>
    {% else %}
        {% include "blog/components/comment_form.html" %}
    {% endif %}
{% endblock content %}

templates/blog/post/detail.html
{% extends "blog/_base.html" %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock title %}
{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|markdown }}
    <p>
        <a href="{% url "blog:post_share" post.id %}">
            Share this post
        </a>
    </p>
    <h2>Similar posts</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        There are no similar posts yet.
    {% endfor %}
    {% with comments.count as total_comments %}
        <h3>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h3>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }} {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There are no comments.</p>
    {% endfor %}
    {% include "components/comment_form.html" %}
{% endblock content %}

templates/blog/post/list.html
{% extends "blog/_base.html" %}
{% load blog_tags %}
{% block title %}My Blog{% endblock title %}
{% block content %}
    <h1>My Blog</h1>
    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h2>
        <p class="tags">Tags:
            {% for tag in post.tags.all %}
                <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                    {{ tag.name }}
                </a>{% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body|markdown|truncatewords_html:30 }}
    {% endfor %}
    {% comment %} le pasamos al template de paginacion el elementos con los posts con el nombre generico page {% endcomment %}
    {% include "components/pagination.html" with page=posts %}
{% endblock content %}

templates/blog/post/search.html
{% extends "blog/_base.html" %}
{% load blog_tags %}
{% block title %}Search{% endblock title %}
{% block content %}
    {% if query %}
        <h1>Posts containing "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
            Found {{ total_results }} result{{total_results|pluralize}}
            {% endwith %}
        </h3>
        {% for post in results %}
            <h4>
                <a href="{{ post.get_absolute_url }}">
                    {{ post.title }}
                </a>
            </h4>
            {{ post.body|markdown|truncatewords_html:12 }}
        {% empty %}
            <p>There are no results for you query.</p>
        {% endfor %}
        <p>
            <a href="{% url "blog:post_search" %}">
                Search again
            </a>
        </p>
    {% else %}
        <h1>Search for posts</h1>
        <form method="GET">
            {{ form.as_p }}
            <button type="submit">Search</button>
        </form>
    {% endif %}
{% endblock content %}

templates/blog/post/share.html
{% extends "blog/_base.html" %}
{% block title %}Share a post{% endblock title %}
{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}
        </p>
    {% else %}
    <h1>Share "{{ post.title }}" by e-mail</h1>
    <form method="post" novalidate>
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit">Send e-mail</button>
    </form>
    {% endif %}
{% endblock content %}